---
- name: Create working directory
  ansible.builtin.file:
    path: '{{ redmine_backup_data_dir }}'
    recurse: yes
    state: directory

- name: If previous data remains, delete the data
  ansible.builtin.file:
    path: "{{ redmine_backup_data_dir }}/{{ redmine_pg_dump_file }}"
    state: absent

- name: Dump Redmine database
  ansible.builtin.shell:
    cmd: "pg_dump -h {{ redmine_db_host }} -U {{ redmine_db_user }} -d {{ redmine_db_name }} > {{ redmine_backup_data_dir }}/{{ redmine_pg_dump_file }}"
    creates: "{{ redmine_backup_data_dir }}/{{ redmine_pg_dump_file }}"
  environment:
    PGPASSWORD: '{{ redmine_db_password }}'

- name: Archive the dump data
  community.general.files.archive:
    path: "{{ redmine_backup_data_dir }}/{{ redmine_pg_dump_file }}"
    dest: "{{ redmine_backup_data_dir }}/{{ redmine_pg_dump_archived_file }}"
    mode: 0755
