---
- name: Create working directory
  ansible.builtin.file:
    path: '{{ redmine_backup_data_dir }}'
    recurse: yes
    state: directory

- name: If previous data remains, delete the data
  ansible.builtin.file:
    path: "{{ redmine_backup_data_dir }}/{{ redmine_archived_pg_dump_file }}"
    state: absent

- name: Dump Redmine database
  ansible.builtin.shell:
    cmd:
      "pg_dump -h {{ redmine_db_host }}
       -U {{ redmine_db_user }}
       --format=t
       -d {{ redmine_db_name }}
       > {{ redmine_backup_data_dir }}/{{ redmine_archived_pg_dump_file }}"
    creates: "{{ redmine_backup_data_dir }}/{{ redmine_archived_pg_dump_file }}"
  environment:
    PGPASSWORD: '{{ redmine_db_password }}'
